function [mat, eul] = rotmats(eul_angles)
phi = eul_angles(1);
theta = eul_angles(2);
psi = eul_angles(3);

Rpsi = [cos(psi) sin(psi) 0; ...
       -sin(psi) cos(psi) 0; ...
            0       0     1];

Rtheta = [cos(theta)  0  -sin(theta); ...
             0        1       0;      ...
          sin(theta)  0  cos(theta)];

Rphi = [1      0         0; ...
        0   cos(phi)  sin(phi); ...
        0  -sin(phi)  cos(phi)];

mat = Rpsi'*Rtheta'*Rphi';

eul = [1  sin(phi)*tan(theta)  cos(phi)*tan(theta); ...
           0      cos(phi)             -sin(phi); ...
           0  sin(phi)/cos(theta)  cos(phi)/cos(theta)];
end